import type {
  VehicleYear,
  VehicleMake,
  VehicleModel,
  VehicleEngine,
  Category,
  Part,
} from "./api";

export interface PartRecord extends Part {
  categoryId: number;
  engineId: number;
}

export const vehicleYears: VehicleYear[] = [
  { year: 2009 },
  { year: 2010 },
  { year: 2011 },
  { year: 2012 },
  { year: 2013 },
];

export const vehicleMakes: VehicleMake[] = [
  { id: 1, name: "Hyundai", country: "Korea" },
  { id: 2, name: "Honda", country: "Japan" },
  { id: 3, name: "Ford", country: "USA" },
];

export const vehicleModels: VehicleModel[] = [
  { id: 101, name: "Elantra", makeId: 1 },
  { id: 102, name: "Accent", makeId: 1 },
  { id: 201, name: "Civic", makeId: 2 },
  { id: 202, name: "Accord", makeId: 2 },
  { id: 301, name: "F-150", makeId: 3 },
  { id: 302, name: "Fusion", makeId: 3 },
];

export const vehicleEngines: VehicleEngine[] = [
  { id: 1001, name: "2.0L L4", modelId: 101 },
  { id: 1002, name: "1.8L L4", modelId: 101 },
  { id: 1101, name: "1.6L L4", modelId: 102 },
  { id: 2001, name: "1.8L L4", modelId: 201 },
  { id: 2002, name: "2.4L L4", modelId: 202 },
  { id: 3001, name: "3.5L V6", modelId: 301 },
  { id: 3002, name: "2.5L L4", modelId: 302 },
];

export const yearToMakeIds: Record<number, number[]> = {
  2009: [1, 2],
  2010: [1, 2, 3],
  2011: [1, 2, 3],
  2012: [1, 2],
  2013: [1, 3],
};

export const modelsByMakeYear: Record<number, Record<number, number[]>> = {
  2009: {
    1: [101, 102],
    2: [201],
  },
  2010: {
    1: [101, 102],
    2: [201, 202],
    3: [301],
  },
  2011: {
    1: [101],
    2: [201, 202],
    3: [301, 302],
  },
  2012: {
    1: [101],
    2: [201, 202],
  },
  2013: {
    1: [101],
    3: [301, 302],
  },
};

export const categories: Category[] = [
  { id: 1, name: "Brake & Wheel Hub", parentId: null },
  { id: 2, name: "Body & Lamp Assembly", parentId: null },
  { id: 3, name: "Engine", parentId: null },
  { id: 4, name: "Suspension", parentId: null },
  { id: 5, name: "Cooling System", parentId: null },
  { id: 101, name: "Brake Pad", parentId: 1 },
  { id: 102, name: "Brake Rotor", parentId: 1 },
  { id: 103, name: "Wheel Bearing & Hub", parentId: 1 },
  { id: 201, name: "Headlight", parentId: 2 },
  { id: 202, name: "Tail Lamp", parentId: 2 },
  { id: 301, name: "Oil Filter", parentId: 3 },
  { id: 302, name: "Spark Plug", parentId: 3 },
  { id: 401, name: "Strut Assembly", parentId: 4 },
  { id: 402, name: "Control Arm", parentId: 4 },
  { id: 501, name: "Radiator", parentId: 5 },
  { id: 502, name: "Thermostat", parentId: 5 },
];

export const partCatalog: PartRecord[] = [
  {
    id: 5001,
    brand: "Raybestos",
    partNumber: "MZG813CH",
    description: "Ceramic brake pads with installation hardware included.",
    price: 15.36,
    tier: "daily_driver",
    warranty: "30 day warranty",
    stock: 18,
    position: "Rear",
    categoryId: 101,
    engineId: 1001,
  },
  {
    id: 5002,
    brand: "Wagner",
    partNumber: "ZD813",
    description: "ThermoQuiet ceramic pads, low dust for daily driving.",
    price: 17.42,
    tier: "premium",
    warranty: "12 month warranty",
    stock: 9,
    position: "Rear",
    categoryId: 101,
    engineId: 1001,
  },
  {
    id: 5003,
    brand: "PowerStop",
    partNumber: "K8061",
    description: "Z17 front brake kit with rotors and pads.",
    price: 98.65,
    tier: "performance",
    warranty: "24 month warranty",
    stock: 6,
    position: "Front",
    categoryId: 102,
    engineId: 1001,
  },
  {
    id: 5004,
    brand: "Centric",
    partNumber: "121.51032",
    description: "OE-style brake rotor, high carbon alloy.",
    price: 28.12,
    tier: "economy",
    warranty: "90 day warranty",
    stock: 21,
    position: "Rear",
    categoryId: 102,
    engineId: 1001,
  },
  {
    id: 5005,
    brand: "SKF",
    partNumber: "BR930865",
    description: "Wheel hub assembly with ABS sensor, bolt-on.",
    price: 74.18,
    tier: "premium",
    warranty: "36 month warranty",
    stock: 4,
    position: "Front",
    categoryId: 103,
    engineId: 1001,
  },
  {
    id: 5006,
    brand: "TYC",
    partNumber: "20-6874-00",
    description: "DOT approved headlamp assembly, clear lens.",
    price: 58.9,
    tier: "daily_driver",
    warranty: "12 month warranty",
    stock: 11,
    position: "Left",
    categoryId: 201,
    engineId: 1001,
  },
  {
    id: 5007,
    brand: "Denso",
    partNumber: "150-1000",
    description: "Long-life spin-on oil filter, OEM fit.",
    price: 7.75,
    tier: "economy",
    warranty: "12 month warranty",
    stock: 32,
    categoryId: 301,
    engineId: 1001,
  },
  {
    id: 5008,
    brand: "NGK",
    partNumber: "BKR5E-11",
    description: "Standard spark plug, copper core.",
    price: 3.9,
    tier: "economy",
    warranty: "12 month warranty",
    stock: 60,
    categoryId: 302,
    engineId: 1001,
  },
  {
    id: 5009,
    brand: "Monroe",
    partNumber: "171482",
    description: "Quick-Strut complete strut assembly.",
    price: 128.4,
    tier: "premium",
    warranty: "36 month warranty",
    stock: 7,
    position: "Front",
    categoryId: 401,
    engineId: 1001,
  },
  {
    id: 5010,
    brand: "Moog",
    partNumber: "RK620448",
    description: "Problem solver control arm with ball joint.",
    price: 64.22,
    tier: "daily_driver",
    warranty: "24 month warranty",
    stock: 13,
    position: "Front Right",
    categoryId: 402,
    engineId: 1001,
  },
  {
    id: 5011,
    brand: "Spectra Premium",
    partNumber: "CU13007",
    description: "All-aluminum radiator, direct replacement.",
    price: 112.55,
    tier: "premium",
    warranty: "18 month warranty",
    stock: 8,
    categoryId: 501,
    engineId: 1001,
  },
  {
    id: 5012,
    brand: "Stant",
    partNumber: "14379",
    description: "OE temperature thermostat with gasket.",
    price: 14.2,
    tier: "economy",
    warranty: "12 month warranty",
    stock: 27,
    categoryId: 502,
    engineId: 1001,
  },
  {
    id: 5101,
    brand: "Akebono",
    partNumber: "ACT914",
    description: "Ultra Premium ceramic pads, low noise.",
    price: 34.6,
    tier: "premium",
    warranty: "24 month warranty",
    stock: 15,
    position: "Front",
    categoryId: 101,
    engineId: 2001,
  },
  {
    id: 5102,
    brand: "Bosch",
    partNumber: "BC905",
    description: "QuietCast rotor with zinc finish.",
    price: 42.9,
    tier: "daily_driver",
    warranty: "24 month warranty",
    stock: 10,
    position: "Rear",
    categoryId: 102,
    engineId: 2001,
  },
  {
    id: 5103,
    brand: "Motorcraft",
    partNumber: "FL-500S",
    description: "Engine oil filter with anti-drainback valve.",
    price: 9.4,
    tier: "daily_driver",
    warranty: "12 month warranty",
    stock: 25,
    categoryId: 301,
    engineId: 3001,
  },
  {
    id: 5104,
    brand: "Motorcraft",
    partNumber: "SP-550",
    description: "Platinum spark plug set for 3.5L.",
    price: 8.6,
    tier: "premium",
    warranty: "24 month warranty",
    stock: 30,
    categoryId: 302,
    engineId: 3001,
  },
  {
    id: 5105,
    brand: "TYC",
    partNumber: "20-9946-00",
    description: "Composite headlamp assembly, DOT approved.",
    price: 72.15,
    tier: "daily_driver",
    warranty: "12 month warranty",
    stock: 5,
    position: "Right",
    categoryId: 201,
    engineId: 3002,
  },
];
